### ISSUE TITLE
PyPI distribution

### ISSUE THREAD

**Issue by maxcountryman** [cemerick/nrepl-python-client#3]
Hi Chas,

I see that you've listed making this a proper Python library as a goal for this project. I'd like to help out with this if possible. I think the `setup.py` script could benefit from additional metadata. After which point you'd then want to publish to PyPI via `$ python setup.py sdist upload`. Once published to PyPI, `nrepl` would be available via `easy_install` or `pip` and usable as a library.

Anyway I'm happy to lend a hand if you'd like!

**Comment by cemerick** [comment]
I know next to nothing about pip, so yeah, any help there is greatly appreciated.  I figure projects providing nREPL support for sublime and textmate would benefit.

Please feel free to add whatever metadata you think should be there (with descriptive filler values, if there's stuff that only I would know, e.g. public keys, etc. if `sdist upload` does signing), and I'll give releasing a shot.

Thanks!

**Comment by maxcountryman** [comment]
PyPI will want you to have your credentials in `~/.pypirc` and `sdist upload` should handle things accordingly.

`~/pypirc` is formatted like this:

```
[server-login]
username:<username>
password:<password>
```

I made a pull request (https://github.com/cemerick/nrepl-python-client/pull/4) with some minimal changes that I hope will get things in line. If you need any help getting it uploaded and such, please don't hesitate to ping me. I'm happy to do whatever I can! :)

**Comment by cemerick** [comment]
Just merged #4, thanks, this is great.  I'll give deployment a whirl sometime soon, and report back. :-D

**Comment by cemerick** [comment]
The lib is now on PyPI, thanks! https://pypi.python.org/pypi/nrepl-python-client
