### ISSUE TITLE
LICENSE file reads MIT, but project states BSD

### ISSUE THREAD

**Issue by maxcountryman** [cemerick/nrepl-python-client#6]
Hi Chas,

I noticed that the LICENSE file reads as the MIT license however the project metadata states its licensed under BSD. I'm guessing the LICENSE file just accidentally includes the wrong license?

Anyway just wanted to let you know as that should probably be updated but I'm not sure which is the one you intended to use for sure.

**Comment by cemerick** [comment]
Good catch, that was an oversight from when I copy/pasted the metadata from…somewhere? :-P  I just released `0.0.3` to avoid any confusion.
