### ISSUE TITLE
None needs to be treated properly!

### ISSUE THREAD

**Issue by Foxboron** [cemerick/nrepl-python-client#9]
Currently writing a nrepl server for Hy, and i have encountered a problem.

Say we send this into the encoder:
{'ns': None, 'value': None, 'session': '45217d9f-ebaa-4a02-803e-38fc8710e225'}

We recive this from the decoder:
{'ns': 'value', 'session': '45217d9f-ebaa-4a02-803e-38fc8710e225'}

Because None is not treated properly, we loose data or it gets merged in rather funny ways.

Another partly related question:
Does nrepl-python-client expect to send in a stream or pr. request? I am not sure what the norm is for nrepl servers.

**Comment by cemerick** [comment]
`None` is not a valid value in nREPL messages.  If a slot has no value, then it simply shouldn't be included in the message.

What do you mean by "pr. request"?  Anyway, nREPL is message-oriented, though most transports do operate over TCP streams.  [Alternative transports](https://github.com/clojure/tools.nrepl/wiki/Extensions) can use whatever transmission mechanism they like.

**Comment by Foxboron** [comment]
But, if None is not a valid value, why is nil a valid value in Clojure's NREPL?

Also, if NREPL operate over TCP streams, nrepl-python-client should end all messages sent with "\r\n".

EDIT: I was actually just being stupid. I noticed now (lol) that nil is actually returned as a string, and not a real value.

**Comment by cemerick** [comment]
`nil` is a valid Clojure value, but it is not within bencode, which is the message encoding used by the default nREPL transport. bencode is not line-oriented, and so line separators are unnecessary.
